on:
  push:
  workflow_dispatch:
    inputs:
      node_inl:
        description: 'Custom net_node.inl url'
        required: false
        default: 'https://raw.githubusercontent.com/monero-project/monero/master/src/p2p/net_node.inl'

jobs:
  check_seed_nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Check tor/ipv4 seed nodes
        run: |
          sudo apt install tor -y
          pip install PySocks
          cd py_levin
          mv ../check_seed_nodes.py .
          python3 check_seed_nodes.py ${{ github.event.inputs.node_inl }}
      - name: Commit files
        run: |
          git add readme.md
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "codeberg"
          git commit -m "Update node status" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
