on:
  workflow_dispatch:
    inputs:
      node_inl:
        description: 'Custom net_node.inl url'
        required: false
        default: ''

jobs:
  check_seed_nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup tor/socks
        uses: tor-actions/setup-tor@main
      - run: |
          pip install PySocks
      - name: Check ipv4/tor seed nodes
        run: |
          export PYTHONPATH="./py_levin/"
          python3 check_seed_nodes.py ${{ github.event.inputs.node_inl }}
