on:
  push:
  workflow_dispatch:
    inputs:
      node_inl:
        description: 'Custom net_node.inl url'
        required: false
        default: 'https://raw.githubusercontent.com/monero-project/monero/master/src/p2p/net_node.inl'

jobs:
  check_seed_nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: recursive

        
      - name: Setup tor/socks
        run: |
          sudo apt install tor -y
          pip install PySocks
          cd py_levin
          mv ../check_seed_nodes.py .
          python3 check_seed_nodes.py ${{ github.event.inputs.node_inl }}
